import img from "./img/main.js"
import option from "./option/main.js"

export default function globe(){
    document.getElementsByTagName("style")[0].innerHTML += `
        .initContentSliderRightSideOmbudsmanWorldBodyLeftSideGlobe{
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            position: relative;
        }`

    const globe = document.createElement("div")
    globe.className = "initContentSliderRightSideOmbudsmanWorldBodyLeftSideGlobe"
    globe.appendChild(img())

    const c = [{t: "Abecásia", top: "29.7%", left: "56.2%"},
        {t: "Afeganistão", top: "35.2%", left: "64.2%"},
        {t: "África do Sul", top: "72%", left: "51.5%"},
        {t: "Albânia", top: "31%", left: "50%"},
        {t: "Alemanha", top: "25.5%", left: "47.2%"},
        {t: "Andorra", top: "30.2%", left: "44.5%"},
        {t: "Angola", top: "62%", left: "49.4%"},
        {t: "Antígua e Barbuda", top: "45%", left: "25%"},
        {t: "Arábia Saudita", top: "41%", left: "58%"},
        {t: "Argélia", top: "38.5%", left: "45%"},
        {t: "Argentina", top: "74%", left: "24.5%"},
        {t: "Armênia", top: "31.5%", left: "57.5%"},
        {t: "Austrália", top: "69%", left: "86.5%"},
        {t: "Áustria", top: "27.2%", left: "48.5%"},
        {t: "Azerbaijão", top: "31.5%", left: "58.3%"},
        {t: "Bahamas", top: "40.5%", left: "19.4%"},
        {t: "Bahrain", top: "39.5%", left: "60%"},
        {t: "Bangladesh", top: "41%", left: "72.5%"},
        {t: "Barbados", top: "48%", left: "25.5%"},
        {t: "Bélgica", top: "25.7%", left: "45.6%"},
        {t: "Belize", top: "44.8%", left: "15.8%"},
        {t: "Bielorrússia", top: "23.9%", left: "52%"},
        {t: "Bolívia", top: "64.7%", left: "23.3%"},
        {t: "Bósnia e Herzegovina", top: "29.3%", left: "49.4%"},
        {t: "Botswana", top: "67.3%", left: "51.5%"},
        {t: "Brasil", top: "62%", left: "28%"},
        {t: "Brunei", top: "52%", left: "80.9%"},
        {t: "Bulgária", top: "30.1%", left: "51.5%"},
        {t: "Burkina Faso", top: "47.3%", left: "43.5%"},
        {t: "Burundi", top: "56.3%", left: "53.6%"},
        {t: "Butão", top: "38.8%", left: "72.3%"},
        {t: "Cabo Verde", top: "45.5%", left: "36.5%"},
        {t: "Camarões", top: "52%", left: "47.8%"},
        {t: "Camboja", top: "47.5%", left: "77.6%"},
        {t: "Canadá", top: "21%", left: "16%"},
        {t: "Catar", top: "40.5%", left: "60.2%"},
        {t: "Cazaquistão", top: "27%", left: "64%"},
        {t: "Chade", top: "46%", left: "49.9%"},
        {t: "Chile", top: "75%", left: "22.2%"},
        {t: "China", top: "34.5%", left: "75%"},
        {t: "Chipre", top: "34.6%", left: "54.2%"},
        {t: "Colômbia", top: "52.5%", left: "20.1%"},
        {t: "Comores", top: "61%", left: "58.5%"},
        {t: "Congo", top: "54.5%", left: "49%"},
        {t: "Coreia do Norte", top: "31.5%", left: "82%"},
        {t: "Coreia do Sul", top: "33.5%", left: "82.9%"},
        {t: "Costa do Marfim", top: "50%", left: "42.1%"},
        {t: "Costa Rica", top: "49%", left: "16.7%"},
        {t: "Croácia", top: "28.5%", left: "48.8%"},
        {t: "Cuba", top: "42.2%", left: "19%"},
        {t: "Dinamarca", top: "22.8%", left: "46.9%"},
        {t: "Djibuti", top: "48%", left: "57.7%"},
        {t: "Dominica", top: "46.2%", left: "25.5%"},
        {t: "Egito", top: "39.2%", left: "53%"},
        {t: "El Salvador", top: "46.8%", left: "15.3%"},
        {t: "Emirados Árabes Unidos", top: "40.8%", left: "61%"},
        {t: "Equador", top: "55.5%", left: "18.5%"},
        {t: "Eritreia", top: "45.4%", left: "56.2%"},
        {t: "Escócia", top: "22.5%", left: "43.4%"},
        {t: "Eslováquia", top: "26.7%", left: "49.6%"},
        {t: "Eslovênia", top: "28%", left: "48.2%"},
        {t: "Espanha", top: "31.5%", left: "43.1%"},
        {t: "Estados Unidos da América", top: "32%", left: "14%"},
        {t: "Estados Federados da Micronésia", top: "48%", left: "92%"},
        {t: "Estônia", top: "21%", left: "51%"},
        {t: "Eswatini", top: "70%", left: "53.8%"},
        {t: "Etiópia", top: "49.6%", left: "56.7%"},
        {t: "Fiji", top: "67%", left: "96%"},
        {t: "Finlândia", top: "19%", left: "51.1%"},
        {t: "França", top: "28%", left: "45%"},
        {t: "Gabão", top: "54.9%", left: "47.7%"},
        {t: "Gâmbia", top: "46.8%", left: "38.9%"},
        {t: "Gana", top: "50.4%", left: "43.4%"},
        {t: "Geórgia", top: "30.3%", left: "57%"},
        {t: "Granada", top: "33%", left: "43.3%"},
        {t: "Grécia", top: "33%", left: "50.7%"},
        {t: "Guatemala", top: "45.5%", left: "15%"},
        {t: "Guiana", top: "51.5%", left: "24.8%"},
        {t: "Guiné", top: "48.3%", left: "40.5%"},
        {t: "Guiné-Bissau", top: "47.5%", left: "38.7%"},
        {t: "Guiné-Equatorial", top: "53.7%", left: "47.3%"},
        {t: "Haiti", top: "43.7%", left: "20.6%"},
        {t: "Holanda", top: "24.7%", left: "45.8%"},
        {t: "Honduras", top: "46%", left: "16.2%"},
        {t: "Hungria", top: "27.6%", left: "49.8%"},
        {t: "Iêmen", top: "46%", left: "58%"},
        {t: "Índia", top: "42%", left: "69%"},
        {t: "Indonésia", top: "55%", left: "80.5%"},
        {t: "Inglaterra", top: "24.6%", left: "43.9%"},
        {t: "Irã", top: "36%", left: "61%"},
        {t: "Iraque", top: "35.3%", left: "57.3%"},
        {t: "Irlanda", top: "24.6%", left: "42%"},
        {t: "Irlanda do Norte", top: "23.7%", left: "42.3%"},
        {t: "Islândia", top: "18%", left: "40%"},
        {t: "Israel", top: "36%", left: "55%"},
        {t: "Itália", top: "30%", left: "47.8%"},
        {t: "Jamaica", top: "44.5%", left: "19.5%"},
        {t: "Japão", top: "33.3%", left: "86.3%"},
        {t: "Jordânia", top: "36.5%", left: "56%"},
        {t: "Kiribati", top: "55%", left: "97%"},
        {t: "Kosovo", top: "30.2%", left: "50.5%"},
        {t: "Kuwait", top: "37.5%", left: "59%"},
        {t: "Laos", top: "42.2%", left: "77.3%"},
        {t: "Macedônia do Norte", top: "31.2%", left: "50.8%"},
        {t: "Madagascar", top: "66%", left: "58.7%"},
        {t: "Malásia", top: "52.4%", left: "77%"},
        {t: "Malawi", top: "62.5%", left: "54.8%"},
        {t: "Maldivas", top: "52.5%", left: "67.5%"},
        {t: "Mali", top: "44%", left: "43.3%"},
        {t: "Malta", top: "34%", left: "48.5%"},
        {t: "Marrocos", top: "36%", left: "42%"},
        {t: "Marshall", top: "45%", left: "99%"},
        {t: "Maurícia", top: "66.5%", left: "61.5%"},
        {t: "Mauritânia", top: "42.5%", left: "40.3%"},
        {t: "México", top: "42%", left: "11.7%"},
        {t: "Mianmar", top: "42%", left: "74.5%"},
        {t: "Moçambique", top: "65%", left: "55%"},
        {t: "Moldávia", top: "27.3%", left: "52.4%"},
        {t: "Mônaco", top: "29.7%", left: "46%"},
        {t: "Mongólia", top: "27.9%", left: "74%"},
        {t: "Montenegro", top: "29.5%", left: "50.1%"},
        {t: "Noruega", top: "20%", left: "46.5%"},
        {t: "Nova Zelândia", top: "72%", left: "94%"},
        {t: "Polônia", top: "24.7%", left: "49.5%"},
        {t: "Portugal", top: "32%", left: "41.6%"},
        {t: "Suécia", top: "20.5%", left: "48.3%"},
        ]

    for(let i = 0; i < c.length; i++){
        globe.appendChild(option(c[i].t, c[i].top, c[i].left))
    }
    return(globe)
}