import option from "./option/main.js"

export default function rightSide(){
    document.getElementsByTagName("style")[0].innerHTML += `
        .initContentSliderRightSideOmbudsmanWorldBodyRightSide{
            width: 50%;
            height: 90%;
            padding: 10px;
            overflow: scroll;
        }
        @media screen and (max-width: 1000px){
            .initContentSliderRightSideOmbudsmanWorldBodyRightSide{
                width: 100%;
                height: 100%;
            }
        }`

    const rightSide = document.createElement("div")
    rightSide.className = "initContentSliderRightSideOmbudsmanWorldBodyRightSide"
    const cs = ["Abecásia",
                "Afeganistão",
                "África do Sul",
                "Albânia",
                "Alemanha",
                "Andorra",
                "Angola",
                "Antígua e Barbuda",
                "Arábia Saudita",
                "Argélia",
                "Argentina",
                "Armênia",
                "Austrália",
                "Áustria",
                "Azerbaijão",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Bélgica",
                "Belize",
                "Benim",
                "Bielorrússia",
                "Bolívia",
                "Bósnia e Herzegovina",
                "Botswana",
                "Brasil",
                "Brunei",
                "Bulgária",
                "Burkina Faso",
                "Burundi",
                "Butão",
                "Cabo Verde",
                "Camarões",
                "Camboja",
                "Canadá",
                "Catar",
                "Cazaquistão",
                "Chade",
                "Chile",
                "China",
                "Chipre",
                "Colômbia",
                "Comores",
                "Congo",
                "Coreia do Norte",
                "Coreia do Sul",
                "Costa do Marfim",
                "Costa Rica",
                "Croácia",
                "Cuba",
                "Dinamarca",
                "Djibuti",
                "Dominica",
                "Egito",
                "El Salvador",
                "Emirados Árabes Unidos",
                "Equador",
                "Eritreia",
                "Escócia",
                "Eslováquia",
                "Eslovênia",
                "Espanha",
                "Estados Unidos da América",
                "Estados Federados da Micronésia",
                "Estônia",
                "Eswatini",
                "Etiópia",
                "Fiji",
                "Finlândia",
                "França",
                "Gabão",
                "Gâmbia",
                "Gana",
                "Geórgia",
                "Granada",
                "Grécia",
                "Guatemala",
                "Guiana",
                "Guiné",
                "Guiné-Bissau",
                "Guiné-Equatorial",
                "Haiti",
                "Holanda",
                "Honduras",
                "Hungria",
                "Iêmen",
                "Índia",    
                "Indonésia",
                "Inglaterra",
                "Irã",
                "Iraque",
                "Irlanda",
                "Irlanda do Norte",
                "Islândia",
                "Israel",
                "Itália",
                "Jamaica",
                "Japão",
                "Jordânia",
                "Kiribati",
                "Kosovo",
                "Kuwait",
                "Laos",
                "Macedônia do Norte",
                "Madagascar",
                "Malásia",
                "Malawi",
                "Maldivas",
                "Mali",
                "Malta",
                "Marrocos",
                "Marshall",
                "Maurícia",
                "Mauritânia",
                "México",
                "Mianmar",
                "Moçambique",
                "Moldávia",
                "Mônaco",
                "Mongólia",
                "Montenegro",
                "Noruega",
                "Nova Zelândia",
                "Polônia",
                "Portugal",
                "Suécia"
            ]
    for(let i = 0; i < cs.length; i++){
        rightSide.appendChild(option(cs[i]))
    }
    return(rightSide)
}